import { Palette } from "../palette.slint";

import { SimulationControllerCommand, SimulationControllerType } from "../button.slint";

export struct AddTextFile {
    title: string,
    content: string,
    media_refs: string
}

export component AddTextFileMenu {

    in-out property <SimulationControllerCommand> node_command;
    in-out property <SimulationControllerType> node_type;
    in-out property <string> node_id;

    callback on_ok(node_command: SimulationControllerCommand, node_type: SimulationControllerType, node_id: string, args: AddTextFile);

    width: 1280px;
    height: 720px;

    init => {
        self.visible = false;
    }

    TouchArea {
        width: parent.width;
        height: parent.height;
    }

    Rectangle {
        background: black;
        opacity: 0.75;
    }

    Rectangle {

        width: 480px;
        height: 216px;

        background: Palette.bg;

        VerticalLayout {
            padding: 16px;
            HorizontalLayout {

                Text {
                    text: "Add Text File";
                    font-size: 18px;
                    font-weight: 600;
                    vertical-alignment: center;
                    horizontal-alignment: left;
                    horizontal-stretch: 1; 
                }

                Rectangle {
                    height: 32px;
                    width: 32px;
                    background: area1.has-hover ? #e05244 : Palette.red;

                    area1 := TouchArea {
                        width: parent.width;
                        height: parent.height;
                        clicked => { root.visible = false; }
                    }

                    VerticalLayout {
                        Image {
                            source: @image-url("../../assets/images/icons/close.png");
                        }
                    }
                }
            }

            Text {
                text: "Add Text File";
                font-size: 16px;
                vertical-alignment: center;
                horizontal-alignment: center;
            }

            HorizontalLayout {

                spacing: 16px;

                Rectangle {
                
                    height: 48px;

                    background: Palette.bg_alt;

                    title := TextInput {

                        font-size: 16px;

                        horizontal-alignment: center;
                        vertical-alignment: center;
                    }
                }

                Rectangle {
                
                    height: 48px;

                    background: Palette.bg_alt;

                    content := TextInput {

                        font-size: 16px;

                        horizontal-alignment: center;
                        vertical-alignment: center;
                    }
                }

                Rectangle {

                    width: 96px;

                    area2 := TouchArea {
                        width: parent.width;
                        height: parent.height;

                        clicked => {
                            root.on_ok(root.node_command, root.node_type, root.node_id, {title: title.text, content: content.text, media_refs: media_refs.text});
                            root.visible = false;
                        }
                    }

                    background: area2.has-hover ? Palette.bg_highlight : Palette.bg_alt;

                    Text {
                        text: "OK";
                        font-size: 16px;
                        vertical-alignment: center;
                        horizontal-alignment: center;
                    }
                }
            }

            Rectangle {
                height: 16px;
            }

            Rectangle {
                
                height: 48px;

                background: Palette.bg_alt;

                media_refs := TextInput {

                    font-size: 16px;

                    horizontal-alignment: center;
                    vertical-alignment: center;
                }
            }
        }
    }

    callback grab_focus();
    grab_focus => {
        title.focus();
        title.set-selection-offsets(title.text.character-count, title.text.character-count);
    }
}