import { Palette } from "../palette.slint";

import { SimulationControllerCommand, SimulationControllerType } from "../button.slint";

export struct RemoveSender {
    node_id: string
}

export component RemoveSenderMenu {

    in-out property <SimulationControllerCommand> node_command;
    in-out property <SimulationControllerType> node_type;
    in-out property <string> node_id;

    callback on_ok(node_command: SimulationControllerCommand, node_type: SimulationControllerType, node_id: string, args: RemoveSender);

    width: 1280px;
    height: 720px;

    init => {
        self.visible = false;
    }

    TouchArea {
        width: parent.width;
        height: parent.height;
    }

    Rectangle {
        background: black;
        opacity: 0.75;
    }

    Rectangle {

        width: 480px;
        height: 200px;

        background: Palette.bg;

        VerticalLayout {
            padding: 16px;
            HorizontalLayout {

                Text {
                    text: "Remove Sender";
                    font-size: 18px;
                    font-weight: 600;
                    vertical-alignment: center;
                    horizontal-alignment: left;
                    horizontal-stretch: 1; 
                }

                Rectangle {
                    height: 32px;
                    width: 32px;
                    background: area1.has-hover ? #e05244 : Palette.red;

                    area1 := TouchArea {
                        width: parent.width;
                        height: parent.height;
                        clicked => { root.visible = false; }
                    }

                    VerticalLayout {
                        Image {
                            source: @image-url("../../assets/images/icons/close.png");
                        }
                    }
                }
            }

            Text {
                text: "Enter the Node ID of the neighbor you want to remove.";
                font-size: 16px;
                vertical-alignment: center;
                horizontal-alignment: center;
            }

            HorizontalLayout {

                spacing: 16px;

                Rectangle {
                
                    height: 48px;

                    background: Palette.bg_alt;

                    node_id2 := TextInput {

                        font-size: 16px;

                        horizontal-alignment: center;
                        vertical-alignment: center;

                        input-type: number;
                    }
                }

                Rectangle {

                    width: 96px;

                    area2 := TouchArea {
                        width: parent.width;
                        height: parent.height;

                        clicked => {
                            root.on_ok(root.node_command, root.node_type, root.node_id, {node_id: node_id2.text});
                            root.visible = false;
                        }
                    }

                    background: area2.has-hover ? Palette.bg_highlight : Palette.bg_alt;

                    Text {
                        text: "OK";
                        font-size: 16px;
                        vertical-alignment: center;
                        horizontal-alignment: center;
                    }
                }
            }
        }
    }

    callback grab_focus();
    grab_focus => {
        node_id2.focus();
        node_id2.set-selection-offsets(node_id2.text.character-count, node_id2.text.character-count);
    }
}