[[client]]
id = 1
connected_drone_ids = [9]

[[drone]]
id = 9
connected_node_ids = [1, 3]
pdr = 0.1

[[client]]
id = 2
connected_drone_ids = [3]

[[drone]]
id = 3
connected_node_ids = [2, 4, 5, 6, 9]
pdr = 0.1

[[server]]
id = 4
connected_drone_ids = [3, 7]

[[server]]
id = 5
connected_drone_ids = [3, 7]

[[server]]
id = 6
connected_drone_ids = [3, 7]

[[drone]]
id = 7
connected_node_ids = [4, 5, 6, 8]
pdr = 0.1

[[client]]
id = 8
connected_drone_ids = [7]

