[[client]]
id = 1
connected_drone_ids = [2]

[[drone]]
id = 2
connected_node_ids = [1, 3, 4]
pdr = 0.0

[[drone]]
id = 3
connected_node_ids = [2, 4]
pdr = 0.0

[[server]]
id = 4
connected_drone_ids = [2, 3]
