import { Palette } from "palette.slint";

export component DroneMenu {
    width: 480px;
    height: 200px;

    Rectangle {
        background: Palette.bg;

        VerticalLayout {
            HorizontalLayout {
                padding: 16px;
                alignment: end;

                Rectangle {
                    area1 := TouchArea {
                        width: parent.width;
                        height: parent.height;

                        clicked => {
                            root.visible = false;
                        }
                    }

                    background: area1.has-hover ? #e85d4f : Palette.red;
                    height: 32px;
                    width: 32px;

                    VerticalLayout {
                        Image {
                            source: @image-url("../assets/images/icons/close.png");
                        }
                    }
                }
            }

            Text {
                text: "What do you want to do?";
                font-size: 16px;
                vertical-alignment: center;
                horizontal-alignment: center;
            }

            HorizontalLayout {
                Rectangle {
                    horizontal-stretch: 1;

                    VerticalLayout {
                        padding: 16px;
                        alignment: end;

                        Rectangle {
                            height: 48px;

                            area2 := TouchArea {
                                width: parent.width;
                                height: parent.height;

                                clicked => {
                                    root.visible = false;
                                }
                            }

                            background: area2.has-hover ? Palette.bg_highlight : Palette.bg_alt;

                            VerticalLayout {
                                Text {
                                    text: "Remove Drone";
                                    font-size: 16px;
                                    vertical-alignment: center;
                                    horizontal-alignment: center;
                                }
                            }
                        }
                    }
                }

                Rectangle {
                    horizontal-stretch: 1;

                    VerticalLayout {
                        padding: 16px;
                        alignment: end;

                        Rectangle {
                            height: 48px;

                            area3 := TouchArea {
                                width: parent.width;
                                height: parent.height;

                                clicked => {
                                    root.visible = false;
                                }
                            }

                            background: area3.has-hover ? Palette.bg_highlight : Palette.bg_alt;

                            VerticalLayout {
                                Text {
                                    text: "Crash Drone";
                                    font-size: 16px;
                                    vertical-alignment: center;
                                    horizontal-alignment: center;
                                }
                            }
                        }
                    }
                }
            }
        }
    }
}
